 devices([
    "iPhone Xs Max",
    "iPhone 8 Plus",
    "iPad Pro (12.9-inch) (2nd generation)",
    "iPad Pro (12.9-inch) (3rd generation)"
 ])

 languages([
   "en-US",
    ["es"]
 ])

scheme("emojiply")

output_directory("./fastlane/screenshots")

clear_previous_screenshots(true)

override_status_bar(true)

